development:
  adapter: postgresql
  encoding: unicode
  database: webt
  pool: 5
  username: artem
  password: passwd

test:
  adapter: postgresql
  encoding: unicode
  database: webt
  pool: 5
  username: artem
  password: passwd
